### PR TITLE
Add wrapper icd

### PR DESCRIPTION
**Pull request by Thaodan**
credit goes to /leomaxx/ the creator of the [[https://github.com/leonmaxx/primus-vk-rpm][rpm package]].

### CODE REVIEW

**Comment by felixdoerre** [comment]
Why not call it  `nv_vulkan_wrapper.json` to fit the corresponding source file?

**Comment by Thaodan** [comment]
Because I marched the rpm pkg. I renamed the file according to your suggestion.

**Comment by felixdoerre** [comment]
Discussion on another issue made me thinking: We'd have to adjust the version to the version of the nvidia-json file. So having such a file fit all nvidia drivers is not possible.

**Comment by Thaodan** [comment]
You can depend on the current nvidia driver at build time.
A hook would be possible to however this shouldn't go to /usr.
I think thats something that needs to be watched for at package level.

**Pull request merged**
